### ISSUE TITLE
Лаб 2

### ISSUE THREAD

**Issue by lasbio** [MishinaDiana/DB-lab#1]
Задания 1-3 - выполнены.
Задания 4-14 - отсутствуют.

**Comment by MishinaDiana** [comment]
Доделала. Не успела все за один присест выполнить, нужно было отлучиться.

**Comment by lasbio** [comment]
7,9 - неверно
8 - лишний AS
11 - лишний AS, грамматическая ошибка
14 - лишний AS, проще вывести стоимость

**Comment by MishinaDiana** [comment]
Исправила.

**Comment by lasbio** [comment]
1. Не выполнен пункт 1 задания ("сохранить в корне проекта") и пункт 5 ("Внесите файл создания базы данных в gitignore")
2. задание 10 - в задании нет требования сортировки, т.е. надо отобрать первых 10 членов клуба. А у вас отобраны первые 10 по алфавиту.

**Comment by MishinaDiana** [comment]
В задании требуется сортировка, вот: "Task-2-10: Выберите 10 фамилий членов клуба упорядочите их по алфавиту без повторов."
.gitignore добавила в корень.

**Comment by lasbio** [comment]
1. не верно. Читайте и разбирайтесь, что такое gitignore
2. Задание 10 == отобрать 10, потом отсортировать. У вас отсортировать все,  после отобрать 10.  Результат, как понимаете, разный.

**Comment by MishinaDiana** [comment]
Задание 10 исправила.
