### ISSUE TITLE
Лаб 3

### ISSUE THREAD

**Issue by lasbio** [MishinaDiana/DB-lab#2]
1. Задание 4 - не верно. Отбираются не все члены. Можно проверить, например, для всех членов с фамилией Смит. В базе 5 Смитов, Ваш скрипт возвращает 1 Смита.
2.  Задание 5 - Не верно. Записанное Вами условие не верно, оно тождественно (facility LIKE 'Tennis Court 1') or 'Tennis Court 2' , которое эквивалентно условию (facility LIKE 'Tennis Court 1'), т.к. BOOLEAN от выражения 'Tennis Court 2' всегда FALSE;
3. Задание 6 - не верно. Ошибки:  (а) стоимость бронирования = стоимость за слот (полчаса) * кол-во слотов. (б) при объединении все поля должны ссылку на таблицу (т.е. должно быть facilities.membercost, а не membercost и т.п.), (в) использование LIKE для поля типа timestamp. (г) поскольку membercost < guestcost, то написанный скрипт будут отбирать аренды  исключительно по цене для гостя.  
4. Задание 7 - не выполнено.

**Comment by MishinaDiana** [comment]
Исправила.

**Comment by lasbio** [comment]
5 - не точно. А разве в задаче есть условие "теннисный"? А объект "Squash Court" будет переименован в "Squash Court 1" разве он не подпадает под условия задачи?

**Comment by MishinaDiana** [comment]
Исправила. Сразу не заметила, что там есть другие объекты с именем "Court".

**Comment by lasbio** [comment]
Всегда всегда надо исходить только из условий задачи, а не из того, что вы видите в БД в текущий момент.  Значения в базе могут быть изменены в любой момент, т.к. они находятся в общем пользовании.

Теперь правильно.
